title: A Sciolist's Meanderings
author: Jane Seah
email: seah.jane@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  An attempt to overcome chronic procrastination by exempting myself from 
  all content restrictions (other than NSFW). I take at stab at chronicling 
  any sort of learning I undertake, be it in computing, music, film, or politics.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Jane Seah
  tagline: Software Engineer.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

  # generate social links in footer
  social_links:
    twitter: shingkid
    github: shingkid
    linkedIn: in/janeseah
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: janeseah
    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# analytics_id: "UA-158859179-2"
  google_analytics: UA-158859179-2

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite
remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
